In [3]:
import pandas as pd
flight = pd.read_excel('British Airways Summer Schedule Dataset - Forage Data Science Task 1.xlsx')
flight.head()

,FLIGHT_DATE,FLIGHT_TIME,TIME_OF_DAY,AIRLINE_CD,FLIGHT_NO,DEPARTURE_STATION_CD,ARRIVAL_STATION_CD,ARRIVAL_COUNTRY,ARRIVAL_REGION,HAUL,AIRCRAFT_TYPE,FIRST_CLASS_SEATS,BUSINESS_CLASS_SEATS,ECONOMY_SEATS,TIER1_ELIGIBLE_PAX,TIER2_ELIGIBLE_PAX,TIER3_ELIGIBLE_PAX
0,2025-09-02,14:19:00,Afternoon,BA,BA5211,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,10,38
1,2025-06-10,06:42:00,Morning,BA,BA7282,LHR,LAX,USA,North America,LONG,B777,8,49,178,0,7,28
2,2025-10-27,15:33:00,Afternoon,BA,BA1896,LHR,FRA,Germany,Europe,SHORT,A320,0,17,163,0,11,40
3,2025-06-15,18:29:00,Evening,BA,BA5497,LHR,IST,Turkey,Europe,SHORT,A320,0,8,172,0,16,54
4,2025-08-25,20:35:00,Evening,BA,BA1493,LHR,FRA,Germany,Europe,SHORT,A320,0,13,167,0,6,27

In [4]:
flight.columns = flight.columns.str.lower()  # Set the column names to lowercase

In [5]:
flight.columns

Index(['flight_date', 'flight_time', 'time_of_day', 'airline_cd', 'flight_no',
       'departure_station_cd', 'arrival_station_cd', 'arrival_country',
       'arrival_region', 'haul', 'aircraft_type', 'first_class_seats',
       'business_class_seats', 'economy_seats', 'tier1_eligible_pax',
       'tier2_eligible_pax', 'tier3_eligible_pax'],
      dtype='object')

In [6]:
sample_flights = flight[(flight['arrival_region'] == 'North America') & (flight['time_of_day'] == 'Morning')].copy()

In [7]:
sample_flights.loc[:, 'category'] = sample_flights['time_of_day'] + ' - ' + sample_flights['arrival_region']

In [8]:
tier1_pct = 0.8 
tier2_pct = 0.5 
tier3_pct = 0.2

sample_flights.loc[:, 'likely_lounge_users'] = (
    sample_flights['tier1_eligible_pax'] * tier1_pct +
    sample_flights['tier2_eligible_pax'] * tier2_pct +
    sample_flights['tier3_eligible_pax'] * tier3_pct
).astype(int)

In [10]:
sample_flights1 = sample_flights[['category', 'arrival_station_cd','tier1_eligible_pax', 'tier2_eligible_pax', 'tier3_eligible_pax', 'likely_lounge_users']].head()
sample_flights1.head()

,category,arrival_station_cd,tier1_eligible_pax,tier2_eligible_pax,tier3_eligible_pax,likely_lounge_users
1,Morning - North America,LAX,0,7,28,9
11,Morning - North America,LAX,0,5,23,7
30,Morning - North America,JFK,2,4,21,7
31,Morning - North America,ORD,0,18,59,20
33,Morning - North America,JFK,0,2,14,3

In [12]:
sample_flights1.to_excel('sample_flights_export1.xlsx', index=True, sheet_name='Sample Flights', engine='openpyxl')