### Problem:
Suppose you have a text document which contains some information about a topic. But you don’t know what that topic is. Your challenge is to find out the topic without reading the text.

### Importing Data

In [1]:
# Reading the file using open()
file=open('moon.txt',mode='r',encoding='utf-8')

# Getting text data as string
text=file.read()

# Closing the file
file.close()

In [2]:
print(text)

The moon is the satellite of the earth. It moves round the earth. It shines at night by light reflected from the Sun. It looks beautiful. The bright Moonlight is very soothing. The earthly objects shine like silver in the moonlight. We are fascinated by the enchanting beauty of the Moon. The moon is not as beautiful as it looks. It seems to be lovely when it shines in the sky at night. As a matter of fact it is devoid of plants and animals. The moon is not a suitable place for plants and animals. Therefore, no form of life can be found on the moon. Unlike the earth, the moon has got no atmosphere. Therefore, the lunar days are very hot and the lunar nights are intensely cold. The moon looks beautiful from the earth but in fact it has up forbidding appearance. It is full of rocks and craters. When we look at the moon at night we see some dark spots on it. These dark spots are dangerous rocks and craters. The gravitational pull of the moon is less than that of the earth, so it is difficult to walk on the surface of the Moon. The moon has fascinated man since the beginning of his life on the earth. He has looked at it with wonder. Many poets have composed beautiful poems on the moon. Scientists tried to reveal the mystery of the moon. They wanted to send human to the moon. Several attempts were made to place man on the moon. At last two Americans-Neil Armstrong and Edwin Aldrin-reached the moon on July 21, 1969. They walked on the surface of the moon and collected the lunar rocks. They returned to the earth safely. The American scientists have sent men to the moon several times. Now the moon has been conquered by man. It is no longer a mysterious object. The journey of the moon may be thrilling but it cannot make our life on the earth happy. It is better to have a happy life on the earth then to go to the moon.

### Cleaning Text

In [3]:
import re

# Function for cleaning text
def clean_text(text):
    
    # Lowercasing the text
    text=text.lower()
    
    # Removing comma(,), period(.) and newline character(\n)
    text=re.sub('[,.\n]','',text)
    
    # Replacing hypen with blank space
    text=re.sub('-',' ',text)
    
    return text

In [4]:
# Cleaning Text
cleaned_text=clean_text(text)

In [5]:
print(cleaned_text)

the moon is the satellite of the earth it moves round the earth it shines at night by light reflected from the sun it looks beautiful the bright moonlight is very soothing the earthly objects shine like silver in the moonlight we are fascinated by the enchanting beauty of the moon the moon is not as beautiful as it looks it seems to be lovely when it shines in the sky at night as a matter of fact it is devoid of plants and animals the moon is not a suitable place for plants and animals therefore no form of life can be found on the moon unlike the earth the moon has got no atmosphere therefore the lunar days are very hot and the lunar nights are intensely cold the moon looks beautiful from the earth but in fact it has up forbidding appearance it is full of rocks and craters when we look at the moon at night we see some dark spots on it these dark spots are dangerous rocks and craters the gravitational pull of the moon is less than that of the earth so it is difficult to walk on the surface of the moon the moon has fascinated man since the beginning of his life on the earth he has looked at it with wonder many poets have composed beautiful poems on the moon scientists tried to reveal the mystery of the moon they wanted to send human to the moon several attempts were made to place man on the moon at last two americans neil armstrong and edwin aldrin reached the moon on july 21 1969 they walked on the surface of the moon and collected the lunar rocks they returned to the earth safely the american scientists have sent men to the moon several times now the moon has been conquered by man it is no longer a mysterious object the journey of the moon may be thrilling but it cannot make our life on the earth happy it is better to have a happy life on the earth then to go to the moon

### Finding most frequent words

In [6]:
import spacy

In [7]:
# Loading spacy model
nlp=spacy.load('en_core_web_sm')

In [8]:
# creating doc object
doc=nlp(cleaned_text)

In [9]:
words_dict={}

# Add word-count pair to the dictionary
for token in doc:
    # Check if the word is already in dictionary 
    if token.text in words_dict:
        # Increment count of word by 1 
        words_dict[token.text]=words_dict[token.text]+1
    else:
        # Add the word to dictionary with count 1 
        words_dict[token.text]=1

In [10]:
import pandas as pd

In [11]:
# Creating a dataframe from dictionary
df = pd.DataFrame({'word':list(words_dict.keys()), 'count':list(words_dict.values())})

In [12]:
# Sorting dataframe in descending order
df.sort_values(by='count',ascending=False,inplace=True,ignore_index=True)

In [13]:
print('Shape=>',df.shape)
df.head(5)

Shape=> (151, 2)

   word  count
0   the     47
1  moon     21
2    it     15
3    of     13
4    to     11

# What are Stop words?
Stopwords are the most common words in a language which are added to make things more understandable to humans. Like in English we have `a, an, the, for, where, when, at,` etc. These words are removed during text pre-processing phase because these words do not add much value to the meaning of the document.

Consider a sample sentence:
##### String: "There is a pen on the table."
##### Stopwords: \["There", "is", "a", "on", "the" \]
##### Meaningful words: \["pen", "table"\]

In [14]:
print(nlp.Defaults.stop_words)

{'doing', 'another', 'three', 'put', 'on', 'seems', 'such', 'various', 'whenever', '‘s', 'without', 'but', 'those', 'whereas', 'that', 'namely', 'already', 'can', 'ever', 'only', 'each', 'however', 'twenty', 'has', 'around', 'anyone', 'across', 'used', 'hereby', 'next', 'upon', 'an', 'per', 'us', 'whole', 'side', '‘re', 'sometimes', "'re", 'hundred', 'down', 'except', 'every', 'and', "'ve", 'their', 'ten', 'your', 'well', 'off', 'which', 'all', 'wherever', 'moreover', 'herself', 'keep', 'noone', 'for', 'wherein', '’re', 'a', 'sometime', 'you', '’ve', 'yourselves', 'some', 'nevertheless', 'whither', 'via', 'here', 'just', 'he', 'almost', 'move', 'please', 'become', 'therefore', 'whence', 'go', 'me', 'still', 'due', 'about', 'one', 'within', 'thereby', 'unless', 'seem', 'cannot', 'yourself', 'top', 'does', 'could', 'ca', 'her', 'two', 'meanwhile', 'whereafter', 'get', 'more', 'perhaps', 'thence', 'something', 'what', 'whatever', 'first', 'now', 'though', 'we', 'may', 'made', "'d", "n't", 'thus', 'when', '‘d', 'fifty', 'to', 'must', 'whom', 'together', 'afterwards', 'between', 'formerly', 'front', 'rather', 'becomes', 'even', 'will', 'done', 'becoming', 'herein', 'before', 'ourselves', 'nowhere', 'latterly', 'been', 'up', 'make', 'twelve', 'with', 'nothing', 'our', 'nobody', 'above', 'amount', 'really', 'thereupon', 'after', 'latter', 'in', 'else', 'least', 'thereafter', '‘ve', 'itself', 'would', 'his', 'n‘t', 'anyhow', 'i', 'under', 'the', 'themselves', 'same', 'yet', 'say', 'beforehand', 'call', '’d', 'toward', 'five', 'them', 'own', 'might', 'where', 'towards', 'take', 'no', 'never', 'hereafter', 'indeed', 'because', 'whoever', 'himself', 'none', 'less', 'along', 'otherwise', 'who', 'anyway', 'how', 'whether', '’ll', 'thru', 'why', 'using', 'whereupon', 'yours', 'former', 'give', 'anywhere', '‘ll', 'elsewhere', 'into', 'full', 'again', 'against', '’m', 'show', 'therein', 'name', 'amongst', 'fifteen', 'him', 'eight', 'further', 'much', 'its', 'not', 'few', 'being', 'quite', 'have', 'also', 'am', 'everything', 'hence', 'forty', 'behind', 'are', 'six', 'while', 'until', 'someone', "'s", 'mostly', 'during', 'my', 'anything', 'through', 'myself', 'was', 'since', 'seeming', 'as', 'be', 'everywhere', 'empty', 'throughout', 'should', 'regarding', 'many', 'bottom', 'hereupon', 'besides', 'if', 'other', 'nine', 'enough', 'although', 'then', 'so', "'m", 'these', 'there', 'any', 'part', '’s', '‘m', 'often', 'others', 'most', 'over', "'ll", 'once', 'hers', 'out', 'were', 'from', 'she', 'n’t', 'alone', 'at', 'sixty', 'by', 'somehow', 'always', 'neither', 'is', 'of', 'they', 'ours', 'serious', 'it', 'had', 'whose', 'see', 'back', 'either', 'everyone', 'four', 'third', 'or', 'seemed', 'whereby', 're', 'last', 'mine', 'this', 'beside', 'did', 'below', 'do', 'several', 'both', 'too', 'became', 'than', 'nor', 'beyond', 'somewhere', 'onto', 'eleven', 'among', 'very'}

In [15]:
len(nlp.Defaults.stop_words)

326

In [16]:
# Getting words that are not stopwords
new_tokens=[token.text for token in doc if (token.is_stop == False)]

In [17]:
print(new_tokens)

['moon', 'satellite', 'earth', 'moves', 'round', 'earth', 'shines', 'night', 'light', 'reflected', 'sun', 'looks', 'beautiful', 'bright', 'moonlight', 'soothing', 'earthly', 'objects', 'shine', 'like', 'silver', 'moonlight', 'fascinated', 'enchanting', 'beauty', 'moon', 'moon', 'beautiful', 'looks', 'lovely', 'shines', 'sky', 'night', 'matter', 'fact', 'devoid', 'plants', 'animals', 'moon', 'suitable', 'place', 'plants', 'animals', 'form', 'life', 'found', 'moon', 'unlike', 'earth', 'moon', 'got', 'atmosphere', 'lunar', 'days', 'hot', 'lunar', 'nights', 'intensely', 'cold', 'moon', 'looks', 'beautiful', 'earth', 'fact', 'forbidding', 'appearance', 'rocks', 'craters', 'look', 'moon', 'night', 'dark', 'spots', 'dark', 'spots', 'dangerous', 'rocks', 'craters', 'gravitational', 'pull', 'moon', 'earth', 'difficult', 'walk', 'surface', 'moon', 'moon', 'fascinated', 'man', 'beginning', 'life', 'earth', 'looked', 'wonder', 'poets', 'composed', 'beautiful', 'poems', 'moon', 'scientists', 'tried', 'reveal', 'mystery', 'moon', 'wanted', 'send', 'human', 'moon', 'attempts', 'place', 'man', 'moon', 'americans', 'neil', 'armstrong', 'edwin', 'aldrin', 'reached', 'moon', 'july', '21', '1969', 'walked', 'surface', 'moon', 'collected', 'lunar', 'rocks', 'returned', 'earth', 'safely', 'american', 'scientists', 'sent', 'men', 'moon', 'times', 'moon', 'conquered', 'man', 'longer', 'mysterious', 'object', 'journey', 'moon', 'thrilling', 'life', 'earth', 'happy', 'better', 'happy', 'life', 'earth', 'moon']

In [18]:
new_words_dict={}

# Add word-count pair to the dictionary
for token in new_tokens:
    # Check if the word is already in dictionary 
    if token in new_words_dict:
        # Increment count of word by 1
        new_words_dict[token] = new_words_dict[token]+1
    else:
        # Add the word to dictionary with count 1 
        new_words_dict[token]=1

In [19]:
# Creating a dataframe from dictionary
new_df = pd.DataFrame({'word':list(new_words_dict.keys()), 'count':list(new_words_dict.values())})

In [20]:
# Sorting dataframe in descending order
new_df.sort_values(by='count',ascending=False,inplace=True,ignore_index=True)

In [21]:
print('Shape=>',new_df.shape)
new_df.head(5)

Shape=> (97, 2)

        word  count
0       moon     21
1      earth      9
2  beautiful      4
3       life      4
4      looks      3

Due to stopwords a lot of resources get wasted in storing and pre-processing these. Removing them makes the process of analysis and model building faster because the corpus size gets reduced due to it.

## Remove Stopwords:
- Text Classification
- Caption Generation
- Auto-Tag Generation

## Don't Remove Stopwords:
- Machine Translation
- Language Modeling
- Text Summarization
- Question-Answering Problems

# Reading the file using open()
file=open('switzerland.txt',mode='r',encoding='utf-8')

# Getting text data as string
text=file.read()

# Closing the file
file.close()

# Exercise

In [22]:
# Reading the file using open()
file=open('switzerland.txt',mode='r',encoding='utf-8')

# Getting text data as string
text=file.read()

# Closing the file
file.close()

In [23]:
print(text)

Switzerland, officially the Swiss Confederation, is a country situated in the confluence of Western, Central, and Southern Europe. It is a federal republic composed of 26 cantons, with federal authorities based in Bern. Switzerland is a landlocked country bordered by Italy to the south, France to the west, Germany to the north, and Austria and Liechtenstein to the east. It is geographically divided among the Swiss Plateau, the Alps, and the Jura, spanning a total area of 41,285 km2 (15,940 sq mi), and land area of 39,997 km2 (15,443 sq mi). While the Alps occupy the greater part of the territory, the Swiss population of approximately 8.5 million is concentrated mostly on the plateau, where the largest cities and economic centres are located, among them Zürich, Geneva and Basel, where multiple international organisations are domiciled (such as FIFA, the UN's second-largest Office, and the Bank for International Settlements) and where the main international airports of Switzerland are.

In [24]:
import re

# Function for cleaning text
def clean_text(text):
    
    # Lowercasing the text
    text=text.lower()
    
    # Removing comma(,), period(.) and newline character(\n)
    text=re.sub('[,.\n]','',text)
    
    # Replacing hypen with blank space
    text=re.sub('-',' ',text)
    
    return text

In [25]:
# Cleaning Text
cleaned_text=clean_text(text)
print(cleaned_text)

switzerland officially the swiss confederation is a country situated in the confluence of western central and southern europe it is a federal republic composed of 26 cantons with federal authorities based in bern switzerland is a landlocked country bordered by italy to the south france to the west germany to the north and austria and liechtenstein to the east it is geographically divided among the swiss plateau the alps and the jura spanning a total area of 41285 km2 (15940 sq mi) and land area of 39997 km2 (15443 sq mi) while the alps occupy the greater part of the territory the swiss population of approximately 85 million is concentrated mostly on the plateau where the largest cities and economic centres are located among them zürich geneva and basel where multiple international organisations are domiciled (such as fifa the un's second largest office and the bank for international settlements) and where the main international airports of switzerland are

In [26]:
import spacy
# Loading spacy model
nlp=spacy.load('en_core_web_sm')
# creating doc object
doc=nlp(cleaned_text)   
words_dict={}

# Add word-count pair to the dictionary
for token in doc:
    # Check if the word is already in dictionary 
    if token.text in words_dict:
        # Increment count of word by 1 
        words_dict[token.text]=words_dict[token.text]+1
    else:
        # Add the word to dictionary with count 1 
        words_dict[token.text]=1

In [28]:
words_dict

{'switzerland': 3,
 'officially': 1,
 'the': 18,
 'swiss': 3,
 'confederation': 1,
 'is': 5,
 'a': 4,
 'country': 2,
 'situated': 1,
 'in': 2,
 'confluence': 1,
 'of': 7,
 'western': 1,
 'central': 1,
 'and': 9,
 'southern': 1,
 'europe': 1,
 'it': 2,
 'federal': 2,
 'republic': 1,
 'composed': 1,
 '26': 1,
 'cantons': 1,
 'with': 1,
 'authorities': 1,
 'based': 1,
 'bern': 1,
 'landlocked': 1,
 'bordered': 1,
 'by': 1,
 'italy': 1,
 'to': 4,
 'south': 1,
 'france': 1,
 'west': 1,
 'germany': 1,
 'north': 1,
 'austria': 1,
 'liechtenstein': 1,
 'east': 1,
 'geographically': 1,
 'divided': 1,
 'among': 2,
 'plateau': 2,
 'alps': 2,
 'jura': 1,
 'spanning': 1,
 'total': 1,
 'area': 2,
 '41285': 1,
 'km2': 2,
 '(': 3,
 '15940': 1,
 'sq': 2,
 'mi': 2,
 ')': 3,
 'land': 1,
 '39997': 1,
 '15443': 1,
 'while': 1,
 'occupy': 1,
 'greater': 1,
 'part': 1,
 'territory': 1,
 'population': 1,
 'approximately': 1,
 '85': 1,
 'million': 1,
 'concentrated': 1,
 'mostly': 1,
 'on': 1,
 'where': 3,
 'largest': 2,
 'cities': 1,
 'economic': 1,
 'centres': 1,
 'are': 3,
 'located': 1,
 'them': 1,
 'zürich': 1,
 'geneva': 1,
 'basel': 1,
 'multiple': 1,
 'international': 3,
 'organisations': 1,
 'domiciled': 1,
 'such': 1,
 'as': 1,
 'fifa': 1,
 'un': 1,
 "'s": 1,
 'second': 1,
 'office': 1,
 'bank': 1,
 'for': 1,
 'settlements': 1,
 'main': 1,
 'airports': 1}

In [27]:
import pandas as pd
# Creating a dataframe from dictionary
df = pd.DataFrame({'word':list(words_dict.keys()), 'count':list(words_dict.values())})
# Sorting dataframe in descending order
df.sort_values(by='count',ascending=False,inplace=True,ignore_index=True)
print('Shape=>',df.shape)
df.head(5)

Shape=> (98, 2)

  word  count
0  the     18
1  and      9
2   of      7
3   is      5
4    a      4

In [32]:
print(nlp.Defaults.stop_words)
len(nlp.Defaults.stop_words)

{'doing', 'another', 'three', 'put', 'on', 'seems', 'such', 'various', 'whenever', '‘s', 'without', 'but', 'those', 'whereas', 'that', 'namely', 'already', 'can', 'ever', 'only', 'each', 'however', 'twenty', 'has', 'around', 'anyone', 'across', 'used', 'hereby', 'next', 'upon', 'an', 'per', 'us', 'whole', 'side', '‘re', 'sometimes', "'re", 'hundred', 'down', 'except', 'every', 'and', "'ve", 'their', 'ten', 'your', 'well', 'off', 'which', 'all', 'wherever', 'moreover', 'herself', 'keep', 'noone', 'for', 'wherein', '’re', 'a', 'sometime', 'you', '’ve', 'yourselves', 'some', 'nevertheless', 'whither', 'via', 'here', 'just', 'he', 'almost', 'move', 'please', 'become', 'therefore', 'whence', 'go', 'me', 'still', 'due', 'about', 'one', 'within', 'thereby', 'unless', 'seem', 'cannot', 'yourself', 'top', 'does', 'could', 'ca', 'her', 'two', 'meanwhile', 'whereafter', 'get', 'more', 'perhaps', 'thence', 'something', 'what', 'whatever', 'first', 'now', 'though', 'we', 'may', 'made', "'d", "n't", 'thus', 'when', '‘d', 'fifty', 'to', 'must', 'whom', 'together', 'afterwards', 'between', 'formerly', 'front', 'rather', 'becomes', 'even', 'will', 'done', 'becoming', 'herein', 'before', 'ourselves', 'nowhere', 'latterly', 'been', 'up', 'make', 'twelve', 'with', 'nothing', 'our', 'nobody', 'above', 'amount', 'really', 'thereupon', 'after', 'latter', 'in', 'else', 'least', 'thereafter', '‘ve', 'itself', 'would', 'his', 'n‘t', 'anyhow', 'i', 'under', 'the', 'themselves', 'same', 'yet', 'say', 'beforehand', 'call', '’d', 'toward', 'five', 'them', 'own', 'might', 'where', 'towards', 'take', 'no', 'never', 'hereafter', 'indeed', 'because', 'whoever', 'himself', 'none', 'less', 'along', 'otherwise', 'who', 'anyway', 'how', 'whether', '’ll', 'thru', 'why', 'using', 'whereupon', 'yours', 'former', 'give', 'anywhere', '‘ll', 'elsewhere', 'into', 'full', 'again', 'against', '’m', 'show', 'therein', 'name', 'amongst', 'fifteen', 'him', 'eight', 'further', 'much', 'its', 'not', 'few', 'being', 'quite', 'have', 'also', 'am', 'everything', 'hence', 'forty', 'behind', 'are', 'six', 'while', 'until', 'someone', "'s", 'mostly', 'during', 'my', 'anything', 'through', 'myself', 'was', 'since', 'seeming', 'as', 'be', 'everywhere', 'empty', 'throughout', 'should', 'regarding', 'many', 'bottom', 'hereupon', 'besides', 'if', 'other', 'nine', 'enough', 'although', 'then', 'so', "'m", 'these', 'there', 'any', 'part', '’s', '‘m', 'often', 'others', 'most', 'over', "'ll", 'once', 'hers', 'out', 'were', 'from', 'she', 'n’t', 'alone', 'at', 'sixty', 'by', 'somehow', 'always', 'neither', 'is', 'of', 'they', 'ours', 'serious', 'it', 'had', 'whose', 'see', 'back', 'either', 'everyone', 'four', 'third', 'or', 'seemed', 'whereby', 're', 'last', 'mine', 'this', 'beside', 'did', 'below', 'do', 'several', 'both', 'too', 'became', 'than', 'nor', 'beyond', 'somewhere', 'onto', 'eleven', 'among', 'very'}

326

In [33]:
# Getting words that are not stopwords
new_tokens=[token.text for token in doc if (token.is_stop == False)]
print(new_tokens)

['switzerland', 'officially', 'swiss', 'confederation', 'country', 'situated', 'confluence', 'western', 'central', 'southern', 'europe', 'federal', 'republic', 'composed', '26', 'cantons', 'federal', 'authorities', 'based', 'bern', 'switzerland', 'landlocked', 'country', 'bordered', 'italy', 'south', 'france', 'west', 'germany', 'north', 'austria', 'liechtenstein', 'east', 'geographically', 'divided', 'swiss', 'plateau', 'alps', 'jura', 'spanning', 'total', 'area', '41285', 'km2', '(', '15940', 'sq', 'mi', ')', 'land', 'area', '39997', 'km2', '(', '15443', 'sq', 'mi', ')', 'alps', 'occupy', 'greater', 'territory', 'swiss', 'population', 'approximately', '85', 'million', 'concentrated', 'plateau', 'largest', 'cities', 'economic', 'centres', 'located', 'zürich', 'geneva', 'basel', 'multiple', 'international', 'organisations', 'domiciled', '(', 'fifa', 'un', 'second', 'largest', 'office', 'bank', 'international', 'settlements', ')', 'main', 'international', 'airports', 'switzerland']

In [34]:
new_words_dict={}

# Add word-count pair to the dictionary
for token in new_tokens:
    # Check if the word is already in dictionary 
    if token in new_words_dict:
        # Increment count of word by 1
        new_words_dict[token] = new_words_dict[token]+1
    else:
        # Add the word to dictionary with count 1 
        new_words_dict[token]=1

In [35]:
# Creating a dataframe from dictionary
df = pd.DataFrame({'word':list(new_words_dict.keys()), 'count':list(new_words_dict.values())})
# Sorting dataframe in descending order
df.sort_values(by='count',ascending=False,inplace=True,ignore_index=True)
print('Shape=>',df.shape)
df.head(5)

Shape=> (76, 2)

            word  count
0    switzerland      3
1          swiss      3
2              )      3
3              (      3
4  international      3

In [11]:
text1 = "The quick brown fox jumps over the lazy dog."
import spacy
# Loading spacy model
nlp = spacy.load('en_core_web_sm')
# creating doc object
doc = nlp(text1)
[(token.text, token.lemma_) for token in doc]

[('The', 'the'),
 ('quick', 'quick'),
 ('brown', 'brown'),
 ('fox', 'fox'),
 ('jumps', 'jump'),
 ('over', 'over'),
 ('the', 'the'),
 ('lazy', 'lazy'),
 ('dog', 'dog'),
 ('.', '.')]

In [ ]:
text1 = "The quick brown fox jumps over the lazy dog."
import spacy
# Loading spacy model
nlp = spacy.load('en_core_web_sm')
# creating doc object
doc = nlp(text1)
[(token.text, token.lemma_) for token in doc]

In [22]:
from scipy.spatial import distance
s1 = 'token'
s2 = 'taken'

# Padding the shorter string with spaces
max_len = max(len(s1), len(s2))
s1_padded = s1.ljust(max_len)
s2_padded = s2.ljust(max_len)

hamming_distance = distance.hamming(list(s1_padded), list(s2_padded))
print(f"Hamming Distance between '{s1}' and '{s2}': {hamming_distance}")

Hamming Distance between 'token' and 'taken': 0.2

In [23]:
print(f"Hamming Distance between '{s1}' and '{s2}': {hamming_distance*len(s1)}")

Hamming Distance between 'token' and 'taken': 1.0